version: '2.1'

services:
  rabbit:
    image: rabbit:latest
    env_file: rabbit.env
    expose: 
      - "5672"
    healthcheck:
      test: ["CMD", "check-running.sh"]
      interval: 5s
      timeout: 3s
  srmail:
    image: srmail:latest
    volumes:
      - ~/work/data.dev/srmail.config.json:/app/config.json
      - ~/work/data.dev/srmail.db.sqlite:/app/srmail/db.sqlite
    depends_on:
      rabbit:
        condition: service_healthy
  mail2run:
    image: mail2run:latest
    volumes:
      - ~/work/data.dev/mail2run.config.json:/app/config.json
    depends_on:
      - srmail
  mail2diaspora:
    image: mail2diaspora:latest
    volumes:
      - ~/work/data.dev/mail2diaspora.config.json:/app/config.json
    depends_on:
      - srmail  
  stacosys:
    image: stacosys:latest
    volumes:
      - ~/work/data.dev/stacosys.config.json:/app/config.json
      - ~/work/data.dev/stacosys.db.sqlite:/app/stacosys/db.sqlite
    expose:
      - "8100"
    depends_on:
      rabbit:
        condition: service_healthy
      srmail:
        condition: service_started   
  hugo-serve:
    image: hugo-serve:latest
    ports:
      - "80:80"
    volumes:
      - ~/work/blog:/site
    depends_on:
      - stacosys