version: '2.1'

services:
  rabbit:
    image: rabbit:latest
    env_file: rabbit.env
    expose: 
      - "5672"
      - "15672"
    ports:
      - "15672:15672"
  stacosys:
    image: stacosys:latest
    expose:
      - "8100"
    depends_on:
      - rabbit
  hugo-serve:
    image: hugo-serve:latest
    ports:
      - "80:80"
    volumes:
      - ~/work/blog:/site
    depends_on:
      - stacosys
    restart: always