version: '2.1'

services:
  rabbit:
    image: rabbit:latest
    env_file: rabbit.env
    expose: 
      - "5672"
  stacosys:
    image: stacosys:latest
    volumes:
      - ~/work/data.dev/stacosys.config.json:/app/config.json
      - ~/work/data.dev/stacosys.db.sqlite:/app/stacosys/db.sqlite
    expose:
      - "8100"
    depends_on:
      - rabbit
  srmail:
    image: srmail:latest
    volumes:
      - ~/work/data.dev/srmail.config.json:/app/config.json
      - ~/work/data.dev/srmail.db.sqlite:/app/srmail/db.sqlite
    depends_on:
      - rabbit      
  hugo-serve:
    image: hugo-serve:latest
    ports:
      - "80:80"
    volumes:
      - ~/work/blog:/site
    depends_on:
      - stacosys