version: '3'

services:
  hugo-serve:
    image: hugo-serve:latest
    ports:
      - "80:80"
    volumes:
      - ${SOURCEDIR}/blog:/site
  stacosys:
    image: pythonapp:latest
    environment: 
      APP_NAME: stacosys
      APP_PORT: ${PORT_STACOSYS}
      APP_CONFIG: /app/config.json
    volumes:
      - ${SOURCEDIR}/stacosys:/app/stacosys
      - ${DATADIR}/stacosys/stacosys.config.json:/app/config.json
      - ${DATADIR}/stacosys/stacosys.db.sqlite:/app/stacosys/db.sqlite
      - blog_html:/var/www/html
    expose:
      - ${PORT_STACOSYS}      