version: '3'

services:
  logger:
    image: bobrik/syslog-ng    
    volumes:
      - syslog:/var/log/syslog-ng
    ports:
      - "514:514"
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "${PORT_PORTAINER}:9000"     # The HTTP port      
    expose:
      - ${PORT_PORTAINER}
  rabbit:
    image: rabbit:latest
    environment:
      RABBITMQ_APP_USER: ${RABBITMQ_APP_USER}
      RABBITMQ_APP_PASSWORD: ${RABBITMQ_APP_PASSWORD}
      RABBITMQ_APP_VHOST: ${RABBITMQ_APP_VHOST}
    expose: 
      - "5672"
  srmail:
    image: pythonapp:latest
    environment: 
      APP_NAME: srmail
      APP_CONFIG: /app/config.json    
    volumes:
      - ${SOURCEDIR}/srmail:/app/srmail
      - ${DATADIR}/srmail/srmail.config.json:/app/config.json
      - ${DATADIR}/srmail/srmail.db.sqlite:/app/srmail/db.sqlite
  mail2run:
    image: pythonapp:latest
    environment:       
      APP_NAME: mail2run
      APP_CONFIG: /app/config.json     
    volumes:
      - ${SOURCEDIR}/mail2run:/app/mail2run
      - ${DATADIR}/mail2run/mail2run.config.json:/app/config.json
  mail2diaspora:
    image: pythonapp:latest
    environment:       
      APP_NAME: mail2diaspora
      APP_CONFIG: /app/config.json     
    volumes:
      - ${SOURCEDIR}/mail2diaspora:/app/mail2diaspora
      - ${DATADIR}/mail2diaspora/mail2diaspora.config.json:/app/config.json  

volumes:
  syslog:
  portainer_data: