version: '3'

services:
  logger:
    image: bobrik/syslog-ng    
    volumes:
      - syslog:/var/log/syslog-ng
    ports:
      - "514:514"
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "${PORT_PORTAINER}:9000"    
  glances:
    image: vimagick/glances
    volumes:
      - ./data:/etc/glances
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w
    pid: host
    restart: always      
    expose:
      - 61208
  srmail:
    image: pythonapp:latest
    environment: 
      APP_NAME: srmail
      APP_PORT: ${PORT_SRMAIL}
      APP_CONFIG: /app/config.ini    
    volumes:
      - ${SOURCEDIR}/srmail:/app/srmail
      - ${DATADIR}/srmail/srmail.config.ini:/app/config.ini
      - ${DATADIR}/srmail/srmail.db.sqlite:/app/srmail/db.sqlite
    expose:
      - ${PORT_SRMAIL}
  mail2diaspora:
    image: pythonapp:latest
    environment:       
      APP_NAME: mail2diaspora
      APP_CONFIG: /app/config.json     
    volumes:
      - ${SOURCEDIR}/mail2diaspora:/app/mail2diaspora
      - ${DATADIR}/mail2diaspora/mail2diaspora.config.json:/app/config.json  

volumes:
  syslog:
  portainer_data: