baseURL = "https://blogduyax.madyanne.space"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
title = "Le blog du Yax - SPACE"
theme = "hugo-pure-yax"
preserveTaxonomyNames = false
paginate = 8
enableRobotsTXT = true
pygmentsuseclasses = false
pygmentsstyle = "manni"

[permalinks]
  post = "/:year/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"

[author]
  name = "Yax"
  bio = "Des articles autour du système et de la programmation par un développeur fan de Logiciel Libre, d'Open source et de standards ouverts."
  #picture = "https://www.gravatar.com/avatar/e2ab93953ba8da3348fe4bfbc1ca0d4e"      # optionnel
  picture = "/favicon-160x160.png"
  #email = "blog at yax"                             # optionnel

[params]
  description = "GNU, Linux, BSD et autres libertés"
  more = "La suite..."
  writtenby = "par"
  older = "Anciens"
  newer = "Récents"

[params.widgets]
  categories = true
  categories_label = "Catégories"
  tags = false
  tags_label = "Tags"
  recent_articles = true
  recent_articles_num = 5
  recent_articles_label = "Articles récents"
  stacosys_comments = false
  stacosys_url = "http://stacosys:8100"
  stacosys_token = "9fb3fc042c572cb831005fd16186126765140fa2bd9bb2d4a28e47a9457dc26c"
  feed1_label = "Fil des articles"
  feed1_url = "/index.xml"
  feed2_label = "Fil des commentaires"
  feed2_url = "http://www.madyanne.fr/blogduyax-comments.xml"
