version: '2.1'

services:
  rabbit:
    image: rabbit:latest
    env_file: ~/work/docker.data/rabbit.env
    expose: 
      - "5672"
    healthcheck:
      test: ["CMD", "check-running.sh"]
      interval: 5s
      timeout: 3s
  srmail:
    image: srmail:latest
    volumes:
      - ~/work/docker.data/srmail.config.json:/app/config.json
      - ~/work/docker.data/srmail.db.sqlite:/app/srmail/db.sqlite
    depends_on:
      rabbit:
        condition: service_healthy   
  mail2run:
    image: mail2run:latest
    volumes:
      - ~/work/docker.data/mail2run.config.json:/app/config.json
    depends_on:
      - srmail      
  mail2diaspora:
    image: mail2diaspora:latest
    volumes:
      - ~/work/docker.data/mail2diaspora.config.json:/app/config.json
    depends_on:
      - srmail  
  stacosys:
    image: stacosys:latest
    volumes:
      - ~/work/docker.data/stacosys.config.json:/app/config.json
      - ~/work/docker.data/stacosys.db.sqlite:/app/stacosys/db.sqlite
    expose:
      - "8100"
    depends_on:
      rabbit:
        condition: service_healthy
      srmail:
        condition: service_started                      
  hugo-git-sync:
    image: hugo-git-sync:latest
    environment:
      REPO_LINK: "https://github.com/kianby/blog.git"
      CONFIG_FILE: /config.toml
    volumes:
      - ~/work/docker.data/test/blog.config.toml:/config.toml
      - blog_html:/var/www/html:z 
    depends_on:
      stacosys:
        condition: service_started    
  nginx-blog:
    image: nginx:latest
    depends_on:
      - hugo-git-sync
    volumes:
      - blog_html:/usr/share/nginx/html
  reverse-proxy:
      image: linuxserver/letsencrypt
      environment:
        EMAIL: "admin@madyanne.space"
        URL: "madyanne.space"
        SUBDOMAINS: "blogduyax"
        VALIDATION: "http"
        TZ: "Europe/Paris"
        PUID: 1000
        PGID: 1000
      ports:
        - "80:80"     # The HTTP port
        - "443:443"
      expose:
        - "80"
        - "443"
      volumes:
        - ~/work/docker.data/test/reverseproxy:/config
volumes:
  blog_html:
    driver: local    