version: '2.1'

services:
  rabbit:
    image: rabbitmq:latest
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - hugo-git-sync
    volumes:
      - blog_html:/usr/share/nginx/html
    restart: always
  hugo-git-sync:
    image: hugo-git-sync:latest
    environment:
      REPO_LINK: "https://github.com/kianby/blog.git"
    volumes:
      - blog_html:/var/www/html:z
    restart: always
volumes:
  blog_html:
    driver: local